modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/spoorn/ClimbLaddersFast/issues"
license = "MIT"

[[mods]]
modId = "climbladdersfast"
version = "${version}"
displayName = "Climb Ladders Fast"
authors = "spoorn"
description = '''
Climb ladders, vines, and scaffolding faster
'''
logoFile = "icon.png"

[[dependencies.climbladdersfast]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"
