modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/spoorn/ClimbLaddersFast/issues"
license = "MIT"

[[mods]]
modId = "climbladdersfast"
version = "${version}"
displayName = "Climb Ladders Fast"
authors = "spoorn"
description = '''
Climb ladders, vines, and scaffolding faster
'''
logoFile = "climbladdersfast.png"

[[dependencies.climbladdersfast]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "cloth_config"
mandatory = false
versionRange = "[11,)"
ordering = "NONE"
side = "CLIENT"
