modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/spoorn/ClimbLaddersFast/issues"
license = "MIT"

[[mods]]
modId = "climbladdersfast"
version = "${version}"
displayName = "Climb Ladders Fast"
authors = "spoorn"
description = '''
Climb ladders, vines, and scaffolding faster
'''
logoFile = "climbladdersfast.png"

[[mixins]]
config = "climbladdersfast-common.mixins.json"

[[dependencies.climbladdersfast]]
modId = "neoforge"
mandatory = true
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "minecraft"
mandatory = true
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.climbladdersfast]]
modId = "cloth_config"
mandatory = false
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"
